SKILL_CANONICAL_MAP: dict[str, str] = {
    "python": "python",
    "java": "java",
    "javascript": "javascript",
    "typescript": "typescript",
    "nodejs": "node.js",
    "node.js": "node.js",
    "react": "react",
    "nextjs": "next.js",
    "next.js": "next.js",
    "angular": "angular",
    "vue": "vue",
    "fastapi": "fastapi",
    "django": "django",
    "flask": "flask",
    "spring": "spring",
    "sql": "sql",
    "postgresql": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "redis": "redis",
    "aws": "aws",
    "azure": "azure",
    "gcp": "gcp",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "terraform": "terraform",
    "ci/cd": "ci/cd",
    "gitlab ci": "ci/cd",
    "github actions": "ci/cd",
    "machine learning": "machine learning",
    "deep learning": "deep learning",
    "pandas": "pandas",
    "numpy": "numpy",
    "scikit-learn": "scikit-learn",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
    "spark": "apache spark",
    "apache spark": "apache spark",
    "hadoop": "hadoop",
    "airflow": "airflow",
    "power bi": "power bi",
    "tableau": "tableau",
    "excel": "excel",
    "linux": "linux",
    "graphql": "graphql",
    "rest api": "rest api",
    "microservices": "microservices",
    "c#": "c#",
    "c++": "c++",
    "go": "go",
    "rust": "rust",
    "php": "php",
    "laravel": "laravel",
    "ruby": "ruby",
    "ruby on rails": "ruby on rails",
}


SKILL_PATTERNS = sorted(SKILL_CANONICAL_MAP.keys(), key=len, reverse=True)

